const Flutterwave = require("flutterwave-node-v3");

const flw = new Flutterwave(
  "FLWPUBK-9248bd4d5c8985fc043ea648eafa6c00-X",
  "FLWSECK-8c210fb77ea11c460271faae1c705691-X"
);

module.exports = async (req, res, next) => {
  console.log(req.body, "payments");

  try {
    const payload = {
      tx_ref: "MC-1585230950508",
      amount: "500",
      email: "movers.koodeyo@gmail.com",
      phone_number: "0756360505",
      currency: "UGX",
      fullname: "Baluku Ibrahim",
      redirect_url: "https://rave-webhook.herokuapp.com/receivepayment",
      // voucher: "128373", //This is the voucher code generated by the customer. It is meant to be passed in the initial charge request. (only for Vodafone cash)
      // network: "MTN",
    };

    const response = await flw.MobileMoney.uganda(payload);
    console.log(response);
    res.json(response);
  } catch (error) {
    console.log(error);
  }
};
// const ug_mobile_money = async () => {
//   try {
//     const payload = {
//       tx_ref: "MC-1585230950508",
//       amount: "500",
//       email: "movers.koodeyo@gmail.com",
//       phone_number: "0756360505",
//       currency: "UGX",
//       fullname: "Baluku Ibrahim",
//       redirect_url: "https://rave-webhook.herokuapp.com/receivepayment",
//       // voucher: "128373", //This is the voucher code generated by the customer. It is meant to be passed in the initial charge request. (only for Vodafone cash)
//       // network: "MTN",
//     };

//     const response = await flw.MobileMoney.uganda(payload);
//     console.log(response);
//   } catch (error) {
//     console.log(error);
//   }
// };

// ug_mobile_money();
